name: Build and publish Docker images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
  push:
    tags:
      - '*'

env:
  REPO_NAME: montejojorge/bitcoin-node-dashboard
  GHCR_REPO_NAME: ghcr.io/montejojorge/bitcoin-node-dashboard

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REPO_NAME }}
            ${{ env.GHCR_REPO_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            type=raw,value=${{ github.event.inputs.version }}

      - name: Build & Publish
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
